name: movie_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.5
  cloud_firestore: ^6.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  custom_lint: ^0.7.6

flutter:
  uses-material-design: true
